[package]
name = "mizuki"
version = "0.1.0"
authors = [ "tonymushah <tonymushahDev06@yahoo.com>" ]
description = "A toolkit for building Tauri Plugins that enables type-safe IPC through GraphQL."
edition = "2021"
rust-version = "1.59"
exclude = [ "/webview-dist", "/webview-src", "node_modules" ]
license = "MIT"
repository = "https://github.com/tonymushah/mizuki"
categories = [ "gui", "web-programming" ]
keywords = [ "tauri-plugin", "graphql" ]

[package.metadata.docs.rs]
features = [ "graphiql" ]

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
tauri = "1"
async-graphql = "6"
warp = { version = "0", optional = true }
async-graphql-warp = { version = "6", optional = true }
http = { version = "0", optional = true }

[features]
graphiql = [ "dep:http", "dep:warp", "dep:async-graphql-warp" ]
log = [ "async-graphql/log" ]
tracing = [ "async-graphql/tracing" ]
opentelemetry = [ "async-graphql/opentelemetry" ]
bson = [ "async-graphql/bson" ]
chrono = [ "async-graphql/chrono" ]
chrono-tz = [ "async-graphql/chrono-tz" ]
url = [ "async-graphql/url" ]
uuid = [ "async-graphql/uuid" ]
uuid08 = [ "async-graphql/uuid08" ]
string_number = [ "async-graphql/string_number" ]
dataloader = [ "async-graphql/dataloader" ]
secrecy = [ "async-graphql/secrecy" ]
decimal = [ "async-graphql/decimal" ]
bigdecimal = [ "async-graphql/bigdecimal" ]
cbor = [ "async-graphql/cbor" ]
smol_str = [ "async-graphql/smol_str" ]
hashbrown = [ "async-graphql/hashbrown" ]
time = [ "async-graphql/time" ]
tokio-sync = [ "async-graphql/tokio-sync" ]
fast_chemail = [ "async-graphql/fast_chemail" ]

[dev-dependencies]
rand = "0.8.5"

[workspace]
members = [ "examples/*/src-tauri" ]
