packages:
  - packages/*
  - examples/*

overrides:
  '@sveltejs/kit@>=2.19.0 <=2.49.4': '>=2.49.5'
  cookie@<0.7.0: '>=0.7.0'
  devalue@>=5.1.0 <5.6.2: '>=5.6.2'
  devalue@>=5.3.0 <=5.6.1: '>=5.6.2'
  diff@<8.0.3: '>=8.0.3'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  nanoid@<3.3.8: '>=3.3.8'
  preact@>=10.27.0 <10.27.3: '>=10.27.3'
  serialize-javascript@>=6.0.0 <6.0.2: '>=6.0.2'
