name: Format Rust

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/format-rust.yml'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/format-rust.yml'
      - 'src/**'

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v5
    - name: Install rustfmt with stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
          components: rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --manifest-path=Cargo.toml --all -- --check
