name: Lint Rust

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lint.yml'
      - 'crates/*/src/**'
      - 'examples/*/src-tauri/src/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/lint.yml'
      - 'crates/*/src/**'
      - 'examples/*/src-tauri/src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: make dist dirs
        run: |
          for dir in examples/*; do
            if [ -d "$dir" ]; then
              mkdir "$dir/dist"
            fi
          done
      - name: install webkit2gtk
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install clippy with stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path=Cargo.toml --all-targets --all-features -- -D warnings
          name: clippy
